name: server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  mongo_dart: ^0.7.4+1
  path: ^1.8.0
  shelf: ^1.3.0
  shelf_hotreload: ^1.1.0
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
